### ISSUE TITLE
Receiving multiple repeating notifications now

### ISSUE THREAD

**Issue by vungsung** [rapid7/attackerkb#56]
**Describe the bug**
Receiving multiple repeating notifications of added Rapid7 Analysis of [this topic](https://attackerkb.com/topics/iXY8Fijc0P/multiple-vulnerabilities-in-hp-device-manager?referrer=notificationWeb#rapid7-analysis) in the meantime writing this bug report.

**To Reproduce**
N/A

**Expected behavior**
Stop receiving the same notification each two minutes.

**Screenshots**
(The list is still growing right now)
![](https://user-images.githubusercontent.com/32069685/94956962-95c87700-051f-11eb-8b25-8743bc5df67e.png)

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by ebleiweiss-r7** [comment]
Thanks for the report! The team is aware of the issue, and we've disabled emails until we get this fixed. Sorry for the spam!

**Comment by vungsung** [comment]
Thanks for responding! Good to know the team is aware of the issue.
